name: My Very First Issue
description: Pick this if you came here from our CONTRIBUTING.md
title: "My Very First Issue: [replace GitHub username here]"
labels: ["very first issue"]
body:
  - type: markdown
    value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        "## Make sure to replace [replace GitHub username here] with your GitHub username"
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Whenever I visit the user account page (1-2 times a week)"
    validations:
      required: true
