name: My Very First Issue
description: Pick this if you came here from our CONTRIBUTING.md
title: "My Very First Issue: [replace GitHub username here]"
labels: ["very first issue"]
body:
- type: checkboxes
  attributes:
    description: "### Make sure to replace [replace GitHub username here] in the title with your GitHub username. Once you do, check the box, scroll down, and click submit."
    options:
      - label: "Yes"
        required: true
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true
