name: My Very First Issue
description: Pick this if you came here from our CONTRIBUTING.md
title: "My Very First Issue: [replace GitHub username here]"
labels: ["very first issue"]
body:
- type: checkboxes
  attributes:
    description: Did I replace [replace GitHub username here] in the title with my GitHub username?
    options:
      - label: "Yes"
        required: true
