name: My Very First Issue
description: Pick this if you came here from our CONTRIBUTING.md
title: "My Very First Issue: [replace GitHub username here]"
labels: ["very first issue"]
body:
- type: checkboxes
  attributes:
    description: "### Make sure to replace [replace GitHub username here] in the title with your GitHub username. Once you do, check the box, and click submit!"
    options:
      - label: "Yes"
        required: true
