name: 'Component Issue Form'
description: 'Issue form for Design to Dev hand-off issues concerning components'
title: "[Component]: "
labels: ["role: frontend"]

body:
  - type: markdown
    attributes:
      value: "## Before we begin, please give an appropriate title to the issue. Make sure to include the name or names of the components in question in the title."
  - type: textarea
    id: dependency-explanation
    attributes:
      label: Dependency
      description: If there is a dependency, please explain what it is.
      placeholder: |
        - [ ] Dependency 1
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Please replace [name] with the name or names of the components this issue concerns.
      value: |
        As a designer, we need to create or update our component library so that our designs are reusable and designers and developers are on the same page. For this issue, we will create or make updates to the [name] component.
    validations:
      required: true
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: "Please skip this portion."
      value: |
        - [ ] Item 1
        - [ ] Item 2
    validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue such as links to Figma or a related issue. This can also include files to be worked on, external sites with solutions, documentation, etc."
      value: |
        [Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
    validations:
      required: true
