name: Create Table
on: workflow_dispatch

jobs:
  test_freelance_giggles:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
        
      - name: Move Issue
        id: api-json
        uses: Aveline-art/freelance-giggles@master
        with:
          configFile: './.github/workflows/fgconfig.json'
          myToken: ${{ secrets.GITHUB_TOKEN }}
