name: Add Pull Request Instructions

on:
  pull_request:
    types: [opened, edited]

jobs:
  Add-Pull-Request-Instructions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Create the message to post
      - name: Create Message
        uses: actions/github-script@v4
        id: message
        with:
          script: |
            const script = require('./createMessage.js')
            const message = script({g: github, c: context})
            return JSON.stringify({ message: message, issueNum: context.payload.number })
      
      # Create an artifact with the message
      - name: Create Artifacts
        run: |
          mkdir -p addingPrInstructions/artifact
          echo ${{ steps.message.outputs.result }} > addingPrInstructions/artifact/artifact.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: adding-pr-instructions-artifact
          path: addingPrInstructions/artifact/
