name: Update Team Members


# Run this action at 11:00 (3 am Pacific) on the first Thursday of the month.
on: workflow_dispatch


jobs:
  # This workflow contains a single job called "trim_contirbutors"
  trim_contributors:
    runs-on: ubuntu-latest

    steps:
    # get the day number of the current month
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +\%d)"

    # checkout repo
    - uses: actions/checkout@v2
    - run: |
        ls
        cd github-actions
        cd github-data
        ls
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
      working-directory: ./github-actions/github-data

    # run js file if it is the first Thursday of the month
    - name: Trim Members
      run: node github-actions/github-data/contributors-data.js