name: Add Update Label to Issues Weekly

on: workflow_dispatch

jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        env:
          IN_PROGRESS_COLUMN_ID: ${{ secrets.IN_PROGRESS_COLUMN_ID }}
        with:
          script: |
            const { columnId: IN_PROGRESS_COLUMN_ID } = process.env;
            const script = require('./sampleScript.js');
            script({g: github, c: context, columnId: columnId });
