name: Add Update Label to Issues Weekly

on:
  schedule:
    - cron:  '0 0 * * 5'

jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          script: |
            const script = require('./path/to/script.js')
            console.log(script({github, context}))
