name: Add Update Label to Issues Weekly

on: workflow_dispatch

jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    steps:
    
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: echo "image=123/123:123" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.build-image.outputs.image }}"
      
