name: Add Update Label to Issues Weekly

on: workflow_dispatch

jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          script: |
            const script = require('./sampleScript.js')
            console.log(script({github, context}))
