name: Test job
on:
  push:
    branches:
      - main

env:
  environment: production

jobs:
  deploy:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download poetry
        run: |
          pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Log vars
        run: |
          PREVIOUS_VERSION=$(poetry version --short)
          UPDATED_VERSION=$(poetry version patch --short)
          echo "$GITHUB_ACTOR"
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "CodeArtifact Bot updated package from $PREVIOUS_VERSION to $UPDATED_VERSION"
          git push
