name: Cache Branch Job
on:
  push:
    branches:
      - main

env:
  environment: production

jobs:
  deploy:
    name: Test Branch Cacheing
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log vars
        run: |
          echo "$GITHUB_ACTOR"
          echo "hahah" > test.txt
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -all
          git commit "hahaahahah"
          git push
